name: Upload artifact
on:
  push:
    branches: [ main ]
jobs:
  upload:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: index.md # or path/to/artifact
