name: Upload artifact
on:
  push:
    branches: [ main ]
jobs:
  spelling:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Upload # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./index.md


